### ISSUE TITLE
Access to XMLHttpRequest 

### ISSUE THREAD

**Issue by Zeeshan-Qaisar** [codeyeah/countrycity#125]
Access to XMLHttpRequest at 'https://shivammathur.com/countrycity/countries?_type=query' from origin ' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://shivammathur.github.io' that is not equal to the supplied origin.
GET https://shivammathur.com/countrycity/countries?_type=query net::ERR_FAILED

I am facing this problem when including this library in my codeigniter project . What the cause and how to solve this problem

**Comment by shivammathur** [comment]
`https://shivammathur.com/countrycity/` is not a public API and thus the server is configured to work only for the example on `shivammathur.github.io`. You have to install it on `https://truehelpers.com/` and if you are using example code change
https://github.com/shivammathur/countrycity/blob/da5c59b78f171c18c9d5456515637f6165d28503/example/index.html#L38
to the location of API on your server, say for example `const base= "https://truehelpers.com/countrycity";`
