### ISSUE TITLE
Question about the source of the data

### ISSUE THREAD

**Issue by MedUnes** [codeyeah/countrycity#132]
Hi there, thanks for the project!
I would like to know what's the source/origin you used for building [the data file](https://github.com/shivammathur/countrycity/blob/master/data/geo.json) of your API ?

**Comment by shivammathur** [comment]
There was not a particular source. This was compiled from various sources in public domain and iteratively improved upon.

**Comment by MedUnes** [comment]
would be nice if you mention the "public domain" sources,
for such data, it is very important to know the source on which one could rely.

Thanks.

**Comment by rvalitov** [comment]
Indeed, without a source information it's hard to validate and trust this data.

**Comment by shivammathur** [comment]
@rvalitov 
It is provided as-is, without any warranties (MIT License). You can use you own data which matches this json schema.
```json
{
  country_a: [city_a, city_b, ...],
  country_b: [city_c, city_d, ...],
  ...
}
```
