### ISSUE TITLE
Full cities lists

### ISSUE THREAD

**Issue by Ildar5** [codeyeah/countrycity#82]
Is it possible to add all coutry cities?
I have  checked some countries and there aren't the full list.

**Comment by shivammathur** [comment]
You can edit the [geo.json](https://github.com/shivammathur/countrycity/blob/master/data/geo.json) file to add cities to countries.

Also if you have examples that the missing, please let me know I will update the file here.

**Comment by Ildar5** [comment]
> You can edit the [geo.json](https://github.com/shivammathur/countrycity/blob/master/data/geo.json) file to add cities to countries.
> 
> Also if you have examples that the missing, please let me know I will update the file here.

many UAE  and Uzbekstan cities are missing.

**Comment by shivammathur** [comment]
@Ildar5 Updated the data for `UAE` and `Uzbekstan`.
