### ISSUE TITLE
Ability to filter cities by population?

### ISSUE THREAD

**Issue by alexgarciab** [codeyeah/countrycity#99]
**Is your feature request related to a problem? Please describe.**
For me it is key to be able to have some sort of ability to filter cities within a country. In my scenario, I want to get only the top 5 cities by population per country.

**Describe the solution you'd like**
Ability to filter cities by population or return top 5 cities by population

**Describe alternatives you've considered**
Nothing

**Additional context**
Usually, when dealing with cities, the ones used are the "most important ones", and in this case, for me, the most important ones are the ones that have the most population.

**Comment by shivammathur** [comment]
Current data in the project does not have population information. If you have a opensource data source I can use for this then please re-open the issue.

**Comment by alexgarciab** [comment]
Opensource data: https://datahub.io/core/population
